// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"ntx/internal/data/models"
)

type BackupHistory struct {
	ID         int64          `json:"id"`
	BackupPath string         `json:"backup_path"`
	BackupSize sql.NullInt64  `json:"backup_size"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	RestoredAt sql.NullTime   `json:"restored_at"`
	Notes      sql.NullString `json:"notes"`
}

type CorporateAction struct {
	ID               int64          `json:"id"`
	Symbol           string         `json:"symbol"`
	ActionType       string         `json:"action_type"`
	AnnouncementDate sql.NullTime   `json:"announcement_date"`
	RecordDate       sql.NullTime   `json:"record_date"`
	ExDate           sql.NullTime   `json:"ex_date"`
	Ratio            sql.NullString `json:"ratio"`
	DividendAmount   models.Money   `json:"dividend_amount"`
	Processed        sql.NullBool   `json:"processed"`
	ProcessedDate    sql.NullTime   `json:"processed_date"`
	Notes            sql.NullString `json:"notes"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type MarketDatum struct {
	ID            int64         `json:"id"`
	Symbol        string        `json:"symbol"`
	LastPrice     models.Money  `json:"last_price"`
	ChangeAmount  models.Money  `json:"change_amount"`
	ChangePercent sql.NullInt64 `json:"change_percent"`
	Volume        sql.NullInt64 `json:"volume"`
	Timestamp     sql.NullTime  `json:"timestamp"`
}

type Portfolio struct {
	ID           int64           `json:"id"`
	Symbol       string          `json:"symbol"`
	Quantity     models.Quantity `json:"quantity"`
	AvgCost      models.Money    `json:"avg_cost"`
	PurchaseDate sql.NullTime    `json:"purchase_date"`
	Notes        sql.NullString  `json:"notes"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
}

type StaleMarketDatum struct {
	Symbol          string      `json:"symbol"`
	LatestTimestamp interface{} `json:"latest_timestamp"`
}

type Transaction struct {
	ID          int64           `json:"id"`
	Type        string          `json:"type"`
	Symbol      string          `json:"symbol"`
	Quantity    models.Quantity `json:"quantity"`
	Price       int64           `json:"price"`
	TotalAmount models.Money    `json:"total_amount"`
	Fees        models.Money    `json:"fees"`
	Date        time.Time       `json:"date"`
	Notes       sql.NullString  `json:"notes"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
}
