// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type CorporateActions struct {
	ID               int64          `json:"id"`
	Symbol           string         `json:"symbol"`
	ActionType       string         `json:"action_type"`
	AnnouncementDate time.Time      `json:"announcement_date"`
	RecordDate       time.Time      `json:"record_date"`
	ExecutionDate    sql.NullTime   `json:"execution_date"`
	RatioFrom        sql.NullInt64  `json:"ratio_from"`
	RatioTo          sql.NullInt64  `json:"ratio_to"`
	AmountPaisa      sql.NullInt64  `json:"amount_paisa"`
	Notes            sql.NullString `json:"notes"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type Holdings struct {
	ID               int64         `json:"id"`
	PortfolioID      int64         `json:"portfolio_id"`
	Symbol           string        `json:"symbol"`
	Quantity         int64         `json:"quantity"`
	AverageCostPaisa int64         `json:"average_cost_paisa"`
	LastPricePaisa   sql.NullInt64 `json:"last_price_paisa"`
	CreatedAt        sql.NullTime  `json:"created_at"`
	UpdatedAt        sql.NullTime  `json:"updated_at"`
}

type Portfolios struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Currency    sql.NullString `json:"currency"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Transactions struct {
	ID              int64          `json:"id"`
	PortfolioID     int64          `json:"portfolio_id"`
	Symbol          string         `json:"symbol"`
	TransactionType string         `json:"transaction_type"`
	Quantity        int64          `json:"quantity"`
	PricePaisa      int64          `json:"price_paisa"`
	CommissionPaisa sql.NullInt64  `json:"commission_paisa"`
	TaxPaisa        sql.NullInt64  `json:"tax_paisa"`
	TransactionDate time.Time      `json:"transaction_date"`
	Notes           sql.NullString `json:"notes"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}
