// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countCompanies = `-- name: CountCompanies :one
SELECT COUNT(*) FROM companies
`

func (q *Queries) CountCompanies(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompanies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompaniesBySearch = `-- name: CountCompaniesBySearch :one
SELECT COUNT(*) FROM companies
WHERE symbol LIKE ? COLLATE NOCASE
OR name LIKE ? COLLATE NOCASE
`

type CountCompaniesBySearchParams struct {
	Symbol string `json:"symbol"`
	Name   string `json:"name"`
}

func (q *Queries) CountCompaniesBySearch(ctx context.Context, arg CountCompaniesBySearchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompaniesBySearch, arg.Symbol, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompaniesBySector = `-- name: CountCompaniesBySector :one
SELECT COUNT(*) FROM companies WHERE sector = ?
`

func (q *Queries) CountCompaniesBySector(ctx context.Context, sector string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompaniesBySector, sector)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, symbol, status, email, website, sector, instrument_type, created_at, updated_at FROM companies WHERE symbol = ?
`

func (q *Queries) GetCompany(ctx context.Context, symbol string) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompany, symbol)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Symbol,
		&i.Status,
		&i.Email,
		&i.Website,
		&i.Sector,
		&i.InstrumentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, symbol, status, email, website, sector, instrument_type, created_at, updated_at FROM companies ORDER by symbol LIMIT ? OFFSET ?
`

type ListCompaniesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listCompanies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Symbol,
			&i.Status,
			&i.Email,
			&i.Website,
			&i.Sector,
			&i.InstrumentType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompaniesBySector = `-- name: ListCompaniesBySector :many
SELECT id, name, symbol, status, email, website, sector, instrument_type, created_at, updated_at FROM companies
WHERE sector = ? AND (symbol LIKE ? OR name LIKE ?)
ORDER BY symbol
LIMIT ? OFFSET ?
`

type ListCompaniesBySectorParams struct {
	Sector string `json:"sector"`
	Symbol string `json:"symbol"`
	Name   string `json:"name"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListCompaniesBySector(ctx context.Context, arg ListCompaniesBySectorParams) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listCompaniesBySector,
		arg.Sector,
		arg.Symbol,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Symbol,
			&i.Status,
			&i.Email,
			&i.Website,
			&i.Sector,
			&i.InstrumentType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCompanies = `-- name: SearchCompanies :many
SELECT id, name, symbol, status, email, website, sector, instrument_type, created_at, updated_at FROM companies
WHERE symbol LIKE ? COLLATE NOCASE
OR name LIKE ? COLLATE NOCASE
ORDER BY symbol
LIMIT ? OFFSET ?
`

type SearchCompaniesParams struct {
	Symbol string `json:"symbol"`
	Name   string `json:"name"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) SearchCompanies(ctx context.Context, arg SearchCompaniesParams) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, searchCompanies,
		arg.Symbol,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Symbol,
			&i.Status,
			&i.Email,
			&i.Website,
			&i.Sector,
			&i.InstrumentType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompany = `-- name: UpsertCompany :exec
INSERT INTO companies (id, name, symbol, status, email, website, sector, instrument_type, updated_at)
VALUES (?,?,?,?,?,?,?,?, CURRENT_TIMESTAMP)
ON CONFLICT(symbol) DO UPDATE SET
  name = excluded.name,
  status = excluded.status,
  email = excluded.email,
  website = excluded.website,
  sector = excluded.sector,
  instrument_type = excluded.instrument_type,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertCompanyParams struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Symbol         string         `json:"symbol"`
	Status         string         `json:"status"`
	Email          sql.NullString `json:"email"`
	Website        sql.NullString `json:"website"`
	Sector         string         `json:"sector"`
	InstrumentType string         `json:"instrument_type"`
}

func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) error {
	_, err := q.db.ExecContext(ctx, upsertCompany,
		arg.ID,
		arg.Name,
		arg.Symbol,
		arg.Status,
		arg.Email,
		arg.Website,
		arg.Sector,
		arg.InstrumentType,
	)
	return err
}
