// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: corporate_actions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getCorporateActionsBySymbol = `-- name: GetCorporateActionsBySymbol :many
SELECT ca.id, ca.company_id, ca.fiscal_year, ca.bonus_percentage, ca.right_percentage, ca.cash_dividend, ca.submitted_date FROM corporate_actions ca
JOIN companies c ON c.id = ca.company_id
WHERE c.symbol = ?
ORDER BY ca.submitted_date DESC
`

func (q *Queries) GetCorporateActionsBySymbol(ctx context.Context, symbol string) ([]CorporateAction, error) {
	rows, err := q.db.QueryContext(ctx, getCorporateActionsBySymbol, symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CorporateAction
	for rows.Next() {
		var i CorporateAction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FiscalYear,
			&i.BonusPercentage,
			&i.RightPercentage,
			&i.CashDividend,
			&i.SubmittedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCorporateAction = `-- name: GetLatestCorporateAction :one
SELECT ca.id, ca.company_id, ca.fiscal_year, ca.bonus_percentage, ca.right_percentage, ca.cash_dividend, ca.submitted_date FROM corporate_actions ca
JOIN companies c ON c.id = ca.company_id
WHERE c.symbol = ?
ORDER BY ca.submitted_date DESC
LIMIT 1
`

func (q *Queries) GetLatestCorporateAction(ctx context.Context, symbol string) (CorporateAction, error) {
	row := q.db.QueryRowContext(ctx, getLatestCorporateAction, symbol)
	var i CorporateAction
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FiscalYear,
		&i.BonusPercentage,
		&i.RightPercentage,
		&i.CashDividend,
		&i.SubmittedDate,
	)
	return i, err
}

const listCorporateActionsByCompany = `-- name: ListCorporateActionsByCompany :many
SELECT id, company_id, fiscal_year, bonus_percentage, right_percentage, cash_dividend, submitted_date FROM corporate_actions
WHERE company_id = ?
ORDER BY submitted_date DESC
`

func (q *Queries) ListCorporateActionsByCompany(ctx context.Context, companyID int64) ([]CorporateAction, error) {
	rows, err := q.db.QueryContext(ctx, listCorporateActionsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CorporateAction
	for rows.Next() {
		var i CorporateAction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FiscalYear,
			&i.BonusPercentage,
			&i.RightPercentage,
			&i.CashDividend,
			&i.SubmittedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCorporateAction = `-- name: UpsertCorporateAction :exec
INSERT INTO corporate_actions (company_id, fiscal_year, bonus_percentage, right_percentage, cash_dividend, submitted_date)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(company_id, fiscal_year, submitted_date) DO UPDATE SET
  bonus_percentage = excluded.bonus_percentage,
  right_percentage = excluded.right_percentage,
  cash_dividend = excluded.cash_dividend
`

type UpsertCorporateActionParams struct {
	CompanyID       int64           `json:"company_id"`
	FiscalYear      string          `json:"fiscal_year"`
	BonusPercentage sql.NullFloat64 `json:"bonus_percentage"`
	RightPercentage sql.NullFloat64 `json:"right_percentage"`
	CashDividend    sql.NullFloat64 `json:"cash_dividend"`
	SubmittedDate   sql.NullString  `json:"submitted_date"`
}

func (q *Queries) UpsertCorporateAction(ctx context.Context, arg UpsertCorporateActionParams) error {
	_, err := q.db.ExecContext(ctx, upsertCorporateAction,
		arg.CompanyID,
		arg.FiscalYear,
		arg.BonusPercentage,
		arg.RightPercentage,
		arg.CashDividend,
		arg.SubmittedDate,
	)
	return err
}
