// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Company struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Symbol         string         `json:"symbol"`
	Status         string         `json:"status"`
	Email          sql.NullString `json:"email"`
	Website        sql.NullString `json:"website"`
	Sector         string         `json:"sector"`
	InstrumentType string         `json:"instrument_type"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type CorporateAction struct {
	ID              int64           `json:"id"`
	CompanyID       int64           `json:"company_id"`
	FiscalYear      string          `json:"fiscal_year"`
	BonusPercentage sql.NullFloat64 `json:"bonus_percentage"`
	RightPercentage sql.NullFloat64 `json:"right_percentage"`
	CashDividend    sql.NullFloat64 `json:"cash_dividend"`
	SubmittedDate   sql.NullString  `json:"submitted_date"`
}

type Fundamental struct {
	ID            int64           `json:"id"`
	CompanyID     int64           `json:"company_id"`
	FiscalYear    string          `json:"fiscal_year"`
	Quarter       string          `json:"quarter"`
	Eps           sql.NullFloat64 `json:"eps"`
	PeRatio       sql.NullFloat64 `json:"pe_ratio"`
	BookValue     sql.NullFloat64 `json:"book_value"`
	PaidUpCapital sql.NullFloat64 `json:"paid_up_capital"`
	ProfitAmount  sql.NullFloat64 `json:"profit_amount"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Ownership struct {
	CompanyID       int64           `json:"company_id"`
	ListedShares    sql.NullInt64   `json:"listed_shares"`
	PublicShares    sql.NullInt64   `json:"public_shares"`
	PublicPercent   sql.NullFloat64 `json:"public_percent"`
	PromoterShares  sql.NullInt64   `json:"promoter_shares"`
	PromoterPercent sql.NullFloat64 `json:"promoter_percent"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type Portfolio struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Price struct {
	ID              int64           `json:"id"`
	CompanyID       int64           `json:"company_id"`
	BusinessDate    string          `json:"business_date"`
	OpenPrice       sql.NullFloat64 `json:"open_price"`
	HighPrice       sql.NullFloat64 `json:"high_price"`
	LowPrice        sql.NullFloat64 `json:"low_price"`
	ClosePrice      sql.NullFloat64 `json:"close_price"`
	LastTradedPrice sql.NullFloat64 `json:"last_traded_price"`
	PreviousClose   sql.NullFloat64 `json:"previous_close"`
	ChangeAmount    sql.NullFloat64 `json:"change_amount"`
	ChangePercent   sql.NullFloat64 `json:"change_percent"`
	Volume          sql.NullInt64   `json:"volume"`
	Turnover        sql.NullFloat64 `json:"turnover"`
	Trades          sql.NullInt64   `json:"trades"`
	CreatedAt       time.Time       `json:"created_at"`
}

type Transaction struct {
	ID              int64        `json:"id"`
	PortfolioID     int64        `json:"portfolio_id"`
	StockSymbol     string       `json:"stock_symbol"`
	TransactionType string       `json:"transaction_type"`
	Quantity        int64        `json:"quantity"`
	UnitPrice       float64      `json:"unit_price"`
	TransactionDate time.Time    `json:"transaction_date"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

type User struct {
	ID           int64        `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
