// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Company struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Symbol         string         `json:"symbol"`
	Status         string         `json:"status"`
	Email          sql.NullString `json:"email"`
	Website        sql.NullString `json:"website"`
	Sector         string         `json:"sector"`
	InstrumentType string         `json:"instrument_type"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}
