// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ownership.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getOwnership = `-- name: GetOwnership :one
SELECT company_id, listed_shares, public_shares, public_percent, promoter_shares, promoter_percent, updated_at FROM ownership WHERE company_id = ?
`

func (q *Queries) GetOwnership(ctx context.Context, companyID int64) (Ownership, error) {
	row := q.db.QueryRowContext(ctx, getOwnership, companyID)
	var i Ownership
	err := row.Scan(
		&i.CompanyID,
		&i.ListedShares,
		&i.PublicShares,
		&i.PublicPercent,
		&i.PromoterShares,
		&i.PromoterPercent,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnershipBySymbol = `-- name: GetOwnershipBySymbol :one
SELECT o.company_id, o.listed_shares, o.public_shares, o.public_percent, o.promoter_shares, o.promoter_percent, o.updated_at FROM ownership o
JOIN companies c ON c.id = o.company_id
WHERE c.symbol = ?
`

func (q *Queries) GetOwnershipBySymbol(ctx context.Context, symbol string) (Ownership, error) {
	row := q.db.QueryRowContext(ctx, getOwnershipBySymbol, symbol)
	var i Ownership
	err := row.Scan(
		&i.CompanyID,
		&i.ListedShares,
		&i.PublicShares,
		&i.PublicPercent,
		&i.PromoterShares,
		&i.PromoterPercent,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOwnership = `-- name: UpsertOwnership :exec
INSERT INTO ownership (company_id, listed_shares, public_shares, public_percent, promoter_shares, promoter_percent, updated_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(company_id) DO UPDATE SET
  listed_shares = excluded.listed_shares,
  public_shares = excluded.public_shares,
  public_percent = excluded.public_percent,
  promoter_shares = excluded.promoter_shares,
  promoter_percent = excluded.promoter_percent,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertOwnershipParams struct {
	CompanyID       int64           `json:"company_id"`
	ListedShares    sql.NullInt64   `json:"listed_shares"`
	PublicShares    sql.NullInt64   `json:"public_shares"`
	PublicPercent   sql.NullFloat64 `json:"public_percent"`
	PromoterShares  sql.NullInt64   `json:"promoter_shares"`
	PromoterPercent sql.NullFloat64 `json:"promoter_percent"`
}

func (q *Queries) UpsertOwnership(ctx context.Context, arg UpsertOwnershipParams) error {
	_, err := q.db.ExecContext(ctx, upsertOwnership,
		arg.CompanyID,
		arg.ListedShares,
		arg.PublicShares,
		arg.PublicPercent,
		arg.PromoterShares,
		arg.PromoterPercent,
	)
	return err
}
