// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getLatestPrice = `-- name: GetLatestPrice :one
SELECT id, company_id, business_date, open_price, high_price, low_price, close_price, last_traded_price, previous_close, change_amount, change_percent, volume, turnover, trades, created_at FROM prices
WHERE company_id = ?
ORDER BY business_date DESC
LIMIT 1
`

func (q *Queries) GetLatestPrice(ctx context.Context, companyID int64) (Price, error) {
	row := q.db.QueryRowContext(ctx, getLatestPrice, companyID)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BusinessDate,
		&i.OpenPrice,
		&i.HighPrice,
		&i.LowPrice,
		&i.ClosePrice,
		&i.LastTradedPrice,
		&i.PreviousClose,
		&i.ChangeAmount,
		&i.ChangePercent,
		&i.Volume,
		&i.Turnover,
		&i.Trades,
		&i.CreatedAt,
	)
	return i, err
}

const getPriceByDate = `-- name: GetPriceByDate :one
SELECT id, company_id, business_date, open_price, high_price, low_price, close_price, last_traded_price, previous_close, change_amount, change_percent, volume, turnover, trades, created_at FROM prices
WHERE company_id = ? AND business_date = ?
`

type GetPriceByDateParams struct {
	CompanyID    int64  `json:"company_id"`
	BusinessDate string `json:"business_date"`
}

func (q *Queries) GetPriceByDate(ctx context.Context, arg GetPriceByDateParams) (Price, error) {
	row := q.db.QueryRowContext(ctx, getPriceByDate, arg.CompanyID, arg.BusinessDate)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BusinessDate,
		&i.OpenPrice,
		&i.HighPrice,
		&i.LowPrice,
		&i.ClosePrice,
		&i.LastTradedPrice,
		&i.PreviousClose,
		&i.ChangeAmount,
		&i.ChangePercent,
		&i.Volume,
		&i.Turnover,
		&i.Trades,
		&i.CreatedAt,
	)
	return i, err
}

const listPricesByCompany = `-- name: ListPricesByCompany :many
SELECT id, company_id, business_date, open_price, high_price, low_price, close_price, last_traded_price, previous_close, change_amount, change_percent, volume, turnover, trades, created_at FROM prices
WHERE company_id = ?
ORDER BY business_date DESC
LIMIT ? OFFSET ?
`

type ListPricesByCompanyParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int64 `json:"limit"`
	Offset    int64 `json:"offset"`
}

func (q *Queries) ListPricesByCompany(ctx context.Context, arg ListPricesByCompanyParams) ([]Price, error) {
	rows, err := q.db.QueryContext(ctx, listPricesByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Price
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BusinessDate,
			&i.OpenPrice,
			&i.HighPrice,
			&i.LowPrice,
			&i.ClosePrice,
			&i.LastTradedPrice,
			&i.PreviousClose,
			&i.ChangeAmount,
			&i.ChangePercent,
			&i.Volume,
			&i.Turnover,
			&i.Trades,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPrice = `-- name: UpsertPrice :exec
INSERT INTO prices (
    company_id, business_date, open_price, high_price, low_price, close_price,
    last_traded_price, previous_close, change_amount, change_percent,
    volume, turnover, trades
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(company_id, business_date) DO UPDATE SET
    open_price = excluded.open_price,
    high_price = excluded.high_price,
    low_price = excluded.low_price,
    close_price = excluded.close_price,
    last_traded_price = excluded.last_traded_price,
    previous_close = excluded.previous_close,
    change_amount = excluded.change_amount,
    change_percent = excluded.change_percent,
    volume = excluded.volume,
    turnover = excluded.turnover,
    trades = excluded.trades
`

type UpsertPriceParams struct {
	CompanyID       int64           `json:"company_id"`
	BusinessDate    string          `json:"business_date"`
	OpenPrice       sql.NullFloat64 `json:"open_price"`
	HighPrice       sql.NullFloat64 `json:"high_price"`
	LowPrice        sql.NullFloat64 `json:"low_price"`
	ClosePrice      sql.NullFloat64 `json:"close_price"`
	LastTradedPrice sql.NullFloat64 `json:"last_traded_price"`
	PreviousClose   sql.NullFloat64 `json:"previous_close"`
	ChangeAmount    sql.NullFloat64 `json:"change_amount"`
	ChangePercent   sql.NullFloat64 `json:"change_percent"`
	Volume          sql.NullInt64   `json:"volume"`
	Turnover        sql.NullFloat64 `json:"turnover"`
	Trades          sql.NullInt64   `json:"trades"`
}

func (q *Queries) UpsertPrice(ctx context.Context, arg UpsertPriceParams) error {
	_, err := q.db.ExecContext(ctx, upsertPrice,
		arg.CompanyID,
		arg.BusinessDate,
		arg.OpenPrice,
		arg.HighPrice,
		arg.LowPrice,
		arg.ClosePrice,
		arg.LastTradedPrice,
		arg.PreviousClose,
		arg.ChangeAmount,
		arg.ChangePercent,
		arg.Volume,
		arg.Turnover,
		arg.Trades,
	)
	return err
}
