// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountCompanies(ctx context.Context) (int64, error)
	CountCompaniesBySearch(ctx context.Context, arg CountCompaniesBySearchParams) (int64, error)
	CountCompaniesBySector(ctx context.Context, sector string) (int64, error)
	CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePortfolio(ctx context.Context, arg DeletePortfolioParams) error
	GetCompany(ctx context.Context, symbol string) (Company, error)
	GetCorporateActionsBySymbol(ctx context.Context, symbol string) ([]CorporateAction, error)
	GetHoldingsByPortfolio(ctx context.Context, portfolioID int64) ([]GetHoldingsByPortfolioRow, error)
	GetLatestCorporateAction(ctx context.Context, symbol string) (CorporateAction, error)
	GetLatestFundamental(ctx context.Context, companyID int64) (Fundamental, error)
	GetLatestPrice(ctx context.Context, companyID int64) (Price, error)
	GetLatestPriceBySymbol(ctx context.Context, symbol string) (Price, error)
	GetOwnership(ctx context.Context, companyID int64) (Ownership, error)
	GetOwnershipBySymbol(ctx context.Context, symbol string) (Ownership, error)
	GetPortfolio(ctx context.Context, arg GetPortfolioParams) (Portfolio, error)
	GetPriceByDate(ctx context.Context, arg GetPriceByDateParams) (Price, error)
	GetSectorStats(ctx context.Context, sector string) (GetSectorStatsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]ListCompaniesRow, error)
	ListCompaniesBySector(ctx context.Context, arg ListCompaniesBySectorParams) ([]Company, error)
	ListCorporateActionsByCompany(ctx context.Context, companyID int64) ([]CorporateAction, error)
	ListFundamentalsByCompany(ctx context.Context, companyID int64) ([]Fundamental, error)
	ListLatestPrices(ctx context.Context) ([]Price, error)
	ListPortfoliosByUser(ctx context.Context, userID int64) ([]Portfolio, error)
	ListPricesByCompany(ctx context.Context, arg ListPricesByCompanyParams) ([]Price, error)
	ListTransactionsByPortfolio(ctx context.Context, portfolioID int64) ([]Transaction, error)
	SearchCompanies(ctx context.Context, arg SearchCompaniesParams) ([]Company, error)
	UpsertCompany(ctx context.Context, arg UpsertCompanyParams) error
	UpsertCorporateAction(ctx context.Context, arg UpsertCorporateActionParams) error
	UpsertFundamental(ctx context.Context, arg UpsertFundamentalParams) error
	UpsertOwnership(ctx context.Context, arg UpsertOwnershipParams) error
	UpsertPrice(ctx context.Context, arg UpsertPriceParams) error
}

var _ Querier = (*Queries)(nil)
