// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountCompanies(ctx context.Context) (int64, error)
	CountCompaniesBySearch(ctx context.Context, arg CountCompaniesBySearchParams) (int64, error)
	CountCompaniesBySector(ctx context.Context, sector string) (int64, error)
	GetCompany(ctx context.Context, symbol string) (Company, error)
	GetLatestFundamental(ctx context.Context, companyID int64) (Fundamental, error)
	GetLatestPrice(ctx context.Context, companyID int64) (Price, error)
	GetPriceByDate(ctx context.Context, arg GetPriceByDateParams) (Price, error)
	GetSectorStats(ctx context.Context, sector string) (GetSectorStatsRow, error)
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error)
	ListCompaniesBySector(ctx context.Context, arg ListCompaniesBySectorParams) ([]Company, error)
	ListFundamentalsByCompany(ctx context.Context, companyID int64) ([]Fundamental, error)
	ListLatestPrices(ctx context.Context) ([]Price, error)
	ListPricesByCompany(ctx context.Context, arg ListPricesByCompanyParams) ([]Price, error)
	SearchCompanies(ctx context.Context, arg SearchCompaniesParams) ([]Company, error)
	UpsertCompany(ctx context.Context, arg UpsertCompanyParams) error
	UpsertFundamental(ctx context.Context, arg UpsertFundamentalParams) error
	UpsertPrice(ctx context.Context, arg UpsertPriceParams) error
}

var _ Querier = (*Queries)(nil)
