// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dividend.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getDividends = `-- name: GetDividends :many
SELECT id, symbol, fiscal_year, cash_percent, bonus_percent, headline, published_at FROM dividends
WHERE symbol = ?
ORDER BY fiscal_year DESC
`

func (q *Queries) GetDividends(ctx context.Context, symbol string) ([]Dividend, error) {
	rows, err := q.db.QueryContext(ctx, getDividends, symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dividend
	for rows.Next() {
		var i Dividend
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.FiscalYear,
			&i.CashPercent,
			&i.BonusPercent,
			&i.Headline,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestDividend = `-- name: GetLatestDividend :one
SELECT id, symbol, fiscal_year, cash_percent, bonus_percent, headline, published_at FROM dividends
WHERE symbol = ?
ORDER BY fiscal_year DESC
LIMIT 1
`

func (q *Queries) GetLatestDividend(ctx context.Context, symbol string) (Dividend, error) {
	row := q.db.QueryRowContext(ctx, getLatestDividend, symbol)
	var i Dividend
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.FiscalYear,
		&i.CashPercent,
		&i.BonusPercent,
		&i.Headline,
		&i.PublishedAt,
	)
	return i, err
}

const listDividends = `-- name: ListDividends :many
SELECT id, symbol, fiscal_year, cash_percent, bonus_percent, headline, published_at FROM dividends
ORDER BY fiscal_year DESC, symbol
`

func (q *Queries) ListDividends(ctx context.Context) ([]Dividend, error) {
	rows, err := q.db.QueryContext(ctx, listDividends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dividend
	for rows.Next() {
		var i Dividend
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.FiscalYear,
			&i.CashPercent,
			&i.BonusPercent,
			&i.Headline,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDividend = `-- name: UpsertDividend :exec
INSERT INTO dividends (symbol, fiscal_year, cash_percent, bonus_percent, headline, published_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(symbol, fiscal_year) DO UPDATE SET
    cash_percent = excluded.cash_percent,
    bonus_percent = excluded.bonus_percent,
    headline = excluded.headline,
    published_at = excluded.published_at
`

type UpsertDividendParams struct {
	Symbol       string         `json:"symbol"`
	FiscalYear   string         `json:"fiscal_year"`
	CashPercent  float64        `json:"cash_percent"`
	BonusPercent float64        `json:"bonus_percent"`
	Headline     sql.NullString `json:"headline"`
	PublishedAt  sql.NullString `json:"published_at"`
}

func (q *Queries) UpsertDividend(ctx context.Context, arg UpsertDividendParams) error {
	_, err := q.db.ExecContext(ctx, upsertDividend,
		arg.Symbol,
		arg.FiscalYear,
		arg.CashPercent,
		arg.BonusPercent,
		arg.Headline,
		arg.PublishedAt,
	)
	return err
}
