// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Stock struct {
	Symbol     string `json:"symbol"`
	Name       string `json:"name"`
	Sector     int64  `json:"sector"`
	LastSynced string `json:"last_synced"`
}
