// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getLatestReport = `-- name: GetLatestReport :one
SELECT id, symbol, type, fiscal_year, quarter, revenue, net_income, eps, book_value, npl_ratio, published_at FROM reports
WHERE symbol = ?
ORDER BY fiscal_year DESC, quarter DESC
LIMIT 1
`

func (q *Queries) GetLatestReport(ctx context.Context, symbol string) (Report, error) {
	row := q.db.QueryRowContext(ctx, getLatestReport, symbol)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Type,
		&i.FiscalYear,
		&i.Quarter,
		&i.Revenue,
		&i.NetIncome,
		&i.Eps,
		&i.BookValue,
		&i.NplRatio,
		&i.PublishedAt,
	)
	return i, err
}

const getReports = `-- name: GetReports :many
SELECT id, symbol, type, fiscal_year, quarter, revenue, net_income, eps, book_value, npl_ratio, published_at FROM reports
WHERE symbol = ?
ORDER BY fiscal_year DESC, quarter DESC
`

func (q *Queries) GetReports(ctx context.Context, symbol string) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, getReports, symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Type,
			&i.FiscalYear,
			&i.Quarter,
			&i.Revenue,
			&i.NetIncome,
			&i.Eps,
			&i.BookValue,
			&i.NplRatio,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByType = `-- name: GetReportsByType :many
SELECT id, symbol, type, fiscal_year, quarter, revenue, net_income, eps, book_value, npl_ratio, published_at FROM reports
WHERE symbol = ? AND type = ?
ORDER BY fiscal_year DESC, quarter DESC
LIMIT ?
`

type GetReportsByTypeParams struct {
	Symbol string `json:"symbol"`
	Type   int64  `json:"type"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) GetReportsByType(ctx context.Context, arg GetReportsByTypeParams) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, getReportsByType, arg.Symbol, arg.Type, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Type,
			&i.FiscalYear,
			&i.Quarter,
			&i.Revenue,
			&i.NetIncome,
			&i.Eps,
			&i.BookValue,
			&i.NplRatio,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReport = `-- name: InsertReport :exec
INSERT INTO reports (symbol, type, fiscal_year, quarter, revenue, net_income, eps, book_value, npl_ratio, published_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(symbol, type, fiscal_year, quarter) DO UPDATE SET
    revenue = excluded.revenue,
    net_income = excluded.net_income,
    eps = excluded.eps,
    book_value = excluded.book_value,
    npl_ratio = excluded.npl_ratio,
    published_at = excluded.published_at
`

type InsertReportParams struct {
	Symbol      string          `json:"symbol"`
	Type        int64           `json:"type"`
	FiscalYear  int64           `json:"fiscal_year"`
	Quarter     int64           `json:"quarter"`
	Revenue     sql.NullFloat64 `json:"revenue"`
	NetIncome   sql.NullFloat64 `json:"net_income"`
	Eps         sql.NullFloat64 `json:"eps"`
	BookValue   sql.NullFloat64 `json:"book_value"`
	NplRatio    sql.NullFloat64 `json:"npl_ratio"`
	PublishedAt sql.NullString  `json:"published_at"`
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) error {
	_, err := q.db.ExecContext(ctx, insertReport,
		arg.Symbol,
		arg.Type,
		arg.FiscalYear,
		arg.Quarter,
		arg.Revenue,
		arg.NetIncome,
		arg.Eps,
		arg.BookValue,
		arg.NplRatio,
		arg.PublishedAt,
	)
	return err
}
