// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock.sql

package sqlc

import (
	"context"
)

const getStock = `-- name: GetStock :one
SELECT symbol, name, sector, last_synced FROM stocks WHERE symbol = ? LIMIT 1
`

func (q *Queries) GetStock(ctx context.Context, symbol string) (Stock, error) {
	row := q.db.QueryRowContext(ctx, getStock, symbol)
	var i Stock
	err := row.Scan(
		&i.Symbol,
		&i.Name,
		&i.Sector,
		&i.LastSynced,
	)
	return i, err
}

const listStocks = `-- name: ListStocks :many
SELECT symbol, name, sector, last_synced FROM stocks ORDER BY symbol
`

func (q *Queries) ListStocks(ctx context.Context) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, listStocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.Symbol,
			&i.Name,
			&i.Sector,
			&i.LastSynced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStocksBySector = `-- name: ListStocksBySector :many
SELECT symbol, name, sector, last_synced FROM stocks WHERE sector = ? ORDER BY symbol
`

func (q *Queries) ListStocksBySector(ctx context.Context, sector int64) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, listStocksBySector, sector)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.Symbol,
			&i.Name,
			&i.Sector,
			&i.LastSynced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStock = `-- name: UpsertStock :exec
INSERT INTO stocks (symbol, name, sector, last_synced)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT(symbol) DO UPDATE SET
    name = excluded.name,
    sector = excluded.sector,
    last_synced = excluded.last_synced
`

type UpsertStockParams struct {
	Symbol string `json:"symbol"`
	Name   string `json:"name"`
	Sector int64  `json:"sector"`
}

func (q *Queries) UpsertStock(ctx context.Context, arg UpsertStockParams) error {
	_, err := q.db.ExecContext(ctx, upsertStock, arg.Symbol, arg.Name, arg.Sector)
	return err
}
