// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trading_day.sql

package sqlc

import (
	"context"
)

const getLastTradingDay = `-- name: GetLastTradingDay :one
SELECT date, is_open, status FROM trading_days
WHERE is_open = 1
ORDER BY date DESC
LIMIT 1
`

func (q *Queries) GetLastTradingDay(ctx context.Context) (TradingDay, error) {
	row := q.db.QueryRowContext(ctx, getLastTradingDay)
	var i TradingDay
	err := row.Scan(&i.Date, &i.IsOpen, &i.Status)
	return i, err
}

const getTradingDay = `-- name: GetTradingDay :one
SELECT date, is_open, status FROM trading_days WHERE date = ? LIMIT 1
`

func (q *Queries) GetTradingDay(ctx context.Context, date string) (TradingDay, error) {
	row := q.db.QueryRowContext(ctx, getTradingDay, date)
	var i TradingDay
	err := row.Scan(&i.Date, &i.IsOpen, &i.Status)
	return i, err
}

const listTradingDays = `-- name: ListTradingDays :many
SELECT date, is_open, status FROM trading_days
WHERE date >= ? AND date <= ?
ORDER BY date
`

type ListTradingDaysParams struct {
	Date   string `json:"date"`
	Date_2 string `json:"date_2"`
}

func (q *Queries) ListTradingDays(ctx context.Context, arg ListTradingDaysParams) ([]TradingDay, error) {
	rows, err := q.db.QueryContext(ctx, listTradingDays, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TradingDay
	for rows.Next() {
		var i TradingDay
		if err := rows.Scan(&i.Date, &i.IsOpen, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTradingDay = `-- name: UpsertTradingDay :exec
INSERT INTO trading_days (date, is_open, status)
VALUES (?, ?, ?)
ON CONFLICT(date) DO UPDATE SET
    is_open = excluded.is_open,
    status = excluded.status
`

type UpsertTradingDayParams struct {
	Date   string `json:"date"`
	IsOpen int64  `json:"is_open"`
	Status string `json:"status"`
}

func (q *Queries) UpsertTradingDay(ctx context.Context, arg UpsertTradingDayParams) error {
	_, err := q.db.ExecContext(ctx, upsertTradingDay, arg.Date, arg.IsOpen, arg.Status)
	return err
}
