// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Transaction struct {
	ID              int64
	Scrip           string
	Date            string
	Quantity        int64
	Price           sql.NullInt64
	TransactionType string
	Description     sql.NullString
	CreatedAt       sql.NullTime
}
